services:
  postgres:
    image: postgres:16-alpine
    container_name: x4u_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ${DATA_PATH}/containers/database_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: x4u_adminer
    restart: always
    ports:
      - "8080:8080"
